### Create Goods
POST http://localhost:3000/goods
Content-Type: application/json

{
    "Name": "TestName21",
    "CodeGoods": "TestGoo2dsCode1",
    "Category": "TestCategory1",
    "Procuder": "TestProcuder1",
    "ProductDescription": "TestDescription1",
    "CountInWarehouse": 2,
    "PriceBuy": 21,
    "PriceSell": 32,
    "SerialNumbers": "te2stSerialNumber1"
}

### Find by id goods
GET http://localhost:3000/goods/65b445f482e5238a38353cab


### Find all parametrs
GET http://localhost:3000/goods
Content-Type: application/json

{
}

### Delete goods
DELETE http://localhost:3000/goods/65b445f482e5238a38353cab


### Update goods
PATCH http://localhost:3000/goods/65b450b319049b2c08f9875c
Content-Type: application/json

{
    "Category": "TestCategory1",
    "Procuder": "TestProcuder1"
}
