### Create category
POST http://localhost:3000/categores
Content-Type: application/json

{
    "Name": "TestCategory13"
}

### Find by id category
GET http://localhost:3000/categores/65b44169f90f955ae316bc7d

### Find by param category
GET http://localhost:3000/categores
Content-Type: application/json

{
}

### Delete category
DELETE http://localhost:3000/categores/65b433bdf3db6636fb2e1a35

### Update category
PATCH http://localhost:3000/categores/65b439ed138c0e3f43224028
Content-Type: application/json

{
    "Name": "fwewef"
}